import React, { useState, useEffect } from "react";
import Head from 'next/head'
import DataTable from '../components/table/DataTable'
import styles from '../styles/Home.module.css'
import { COLUMNS } from "../lib/columns";
import { supabase } from "../lib/supabaseClient";


export default function Home() {
  const [loading, setLoading] = useState(true)
  const [data, setData] = useState(null)

  async function getData() {
    try {
      setLoading(true);

      const { data, error, status } = await supabase
        .from('connect_test')
        .select('opensea_id, lowest_ask, market_cap, highest_bid, last_sale_price, name, parallel, rarity, supply, is_se, market_gap, img_url')
        .in('opensea_id', ['19', '12', '10133', '16', '10142', '10109', '10090', '10089', '10114', '10296', '10210'])
        .order('name', { ascending: true });

      if (error && status !== 406) {
        throw error
      }

      if (data) {
        console.log(data);
        setData(data)
      }
    } catch (error) {
      console.log(error.message)
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    getData();
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {loading
        ? 'Loading ...' :
        <DataTable columns={COLUMNS} data={data} />
      }
    </div>
  )
}
